name: chat-app

services:
  backend:
    image: project-chat-service-test
    container_name: chat-app-backend
    networks:
      - shared-network
#    depends_on:
#      dev-environment:mariadb:
#        condition: service_started
    #    environment:
    #      QUARKUS_DATASOURCE_JDBC_URL: jdbc:mariadb://mariadb:3306/elteq_user_service
    #      QUARKUS_DATASOURCE_USERNAME: chat_app
    #      QUARKUS_DATASOURCE_PASSWORD: ybgfcnojcojh6737*^
    ports:
      - "8050:8050"

  ui:
    image: chat-ui
    container_name: chat-app-ui
    networks:
      - shared-network
    depends_on:
      backend:
        condition: service_started
    ports:
      - "5173:5173"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - HOST=0.0.0.0
      - PORT=5173
    restart: unless-stopped

networks:
  shared-network:
    name: project_shared_network
    external: true
    driver: bridge